### PR TITLE
fixing the 'project.version' issue with extensions

### PR DESCRIPTION
**Pull request by rareddy**

### CODE REVIEW

**Comment by heiko-braun** [comment]
thanks @rareddy. let me take a look if this could have any side effects before we merge it.

**Comment by hpehl** [comment]
Hi @rareddy, the extensions mechanism in master is currently "under construction" and needs to be fixed [1]. Do you rely on master or on 2.6.x? Merging for 2.6.x should be possible w/o any side effects. However it might take some time until the extension mechanism for master is fixed.

[1] https://issues.jboss.org/browse/HAL-619

**Comment by rareddy** [comment]
@hpehl currently I am using neither of them, I had to use 2.5.1 (EAP 6.4.Alpha), so I checked out repo using the tag, then locally modified the pom, and then build, then I could run the Teiid's build and release process. I gathered the minimal changes submitted as pull. IMO, making the changes on 2.6.x should help the product build process. You are right, in order for maven to correctly version your pom files during the "release:prepare" this needs to be done differently. One suggestion is pull BOM out of your HAL build, and manage that as separate project, then choose to build the extension projects that co-located inside the HAL as separate projects using BOM, or directly depend on other modules.

**Comment by hpehl** [comment]
Merged as first step to fix [HAL-619](https://issues.jboss.org/browse/HAL-619)

**Pull request closed without merging**
