### PR TITLE
[HAL-776] Unnecessary validation of numeric fields forces user to man…

### PR DESCRIPTION
**Pull request by ryanemerson**
…ually enter even default values when configuring infinispan subsystem

### CODE REVIEW

**Comment by heiko-braun** [comment]
tnx, ryan

**Comment by heiko-braun** [comment]
@ryanemerson we would need the same fix in master

**Comment by ryanemerson** [comment]
@heiko-braun I had a look at the master branch, however my progress was hampered by HAL-773.  My plan was to  implement the master fix for 776 once 773 has been resolved.  

https://issues.jboss.org/browse/HAL-773?jql=project%20%3D%20HAL

**Comment by heiko-braun** [comment]
I understand. That makes sense. I'll let you know when I make progress with HAL-773

**Comment by ryanemerson** [comment]
@heiko-braun I see that HAL-773 has been resolved, I will fix this upstream ASAP.

**Pull request merged**
