### PR TITLE
[HAL-716] Can't change cache store attributes back to false from true

### PR DESCRIPTION
**Pull request by TomasHofman**
https://issues.jboss.org/browse/HAL-716
https://issues.jboss.org/browse/JBEAP-361

### CODE REVIEW

**Comment by heiko-braun** [comment]
The same probablyneeds to be done upon other modifications, i.e. removals of sub resources.

**Comment by TomasHofman** [comment]
Sure.

**Comment by heiko-braun** [comment]
@TomasHofman just checked, i think there are no other cases. tnx for the contribution, once again :)

**Comment by TomasHofman** [comment]
ok, welcome :)

**Pull request merged**
