### PR TITLE
BZ1201685: Deployments name shortened in admin console.

### PR DESCRIPTION
**Pull request by rpelisse**
* Adding fullname to the tooltip.

### CODE REVIEW

**Comment by heiko-braun** [comment]
merged by hpehl

**Comment by hpehl** [comment]
Already merged in https://github.com/hal/core/pull/27

**Comment by wolfc** [comment]
#27 is against master, this one is against 2.5.x and doesn't appear to have been merged.

**Comment by hpehl** [comment]
@wolfc you're right. This got lost somehow. I can provide a back port, but this would require another 2.5.x release.

**Comment by wolfc** [comment]
@hpehl if you can get a 2.5.9 that only contains this additional PR, then that would be great.

**Comment by rpelisse** [comment]
@hpehl .. and let me know if I c

**Comment by hpehl** [comment]
Thanks @rpelisse, but I'm already about to release ;-)

**Comment by hpehl** [comment]
@wolfc Isn't it too late for 2.5.9.Final? 
https://github.com/jbossas/jboss-eap/pull/2534

**Comment by hpehl** [comment]
@wolfc Just released 2.5.9.Final containing fix for BZ1201685
https://github.com/hal/core/commits/2.5.x

**Pull request closed without merging**
