### PR TITLE
Code cleaning - reworking handle to emphasis (...) to centralize code to ease maintenance and limit potential side effect

### PR DESCRIPTION
**Pull request by rpelisse**
Hi,

This PR is on the maintenance, but I'll port it to master if approved. Right now it is mostly here to allow code review and comment from core developpper.

Also, please double check (test) my changes ! Indeed, while rather simple, and clean, they do change things "here and there", leading to potential unseen "side effect".

### CODE REVIEW

**Comment by hpehl** [comment]
LGTM. Could you submit a PR against master? This makes testing easier for me.

**Comment by rpelisse** [comment]
Hi Harald,

Yes, if it's easier, I'll do so (but not before Wednesday saldy, I'm a bit overrun right now...)

**Comment by hpehl** [comment]
No worries, take your time.

**Comment by rpelisse** [comment]
sorry - clicked on the wrong button !

**Comment by rpelisse** [comment]
[PR80](https://github.com/hal/core/pull/80) created for mainstream.

**Comment by rpelisse** [comment]
Linked to [BZ1274816](https://bugzilla.redhat.com/show_bug.cgi?id=1274816).

**Pull request merged**
