### PR TITLE
[HAL-993, JBEAP-2053] Server-group Port-offset overriding not display…

### PR DESCRIPTION
**Pull request by ryanemerson**
…ed in Domain mode

JIRA: https://issues.jboss.org/browse/HAL-993
JBEAP: https://issues.jboss.org/browse/JBEAP-2053

### CODE REVIEW

**Comment by hpehl** [comment]
Thanks for the update @ryanemerson, but I think it's not a good idea to include the effective port setting in the server config view. The view should only contain attributes which the user can modify. I think It's difficult for the user to make a difference between the port offset and the effective port offset. This would require some kind of help text which is hard to implement.   

Instead I suggest to show the port offset in the preview of the selected server. This would also simplify the code to read the port offset: First try to use `/host=<host>/server-config=<server>:read-attribute(name=socket-binding-port-offset)` and then `/server-group=<related-server-group>:read-attribute(name=socket-binding-port-offset)`

**Comment by ryanemerson** [comment]
@hpehl Thanks for the feedback, I'll look into applying this to the preview instead.  

Regarding the DMR address: I originally tried using the method described above, however there is an edge case that this method does not cater for.  Assume that a server-group, "main-server-group" has been defined with a port-offset set to 100 and that a server, "server-one", belongs to this group.  If the user sets the port-offset to 0 in the host.xml for "server-one", then the effective port-offset is 0 due to the overriding rules employed by WFLY.  

However, if you try to determine the effective port-offset using the DMR addresses you stated, AFAIK, you can't differentiate between whether "server-one"'s offset has been set or not, as the default value is zero.  So in such a case, it's not possible to know whether to display 100 (server-group) or 0 (server-one), as there is no way to determine whether 0 is "server-one"'s overridden or default value.  

From the CLI, the only way I was able to accurately (and succinctly) determine the effective port-offset was via `/host=<host>/server=<server>:read-children-resources(child-type=socket-binding-group)`

**Comment by hpehl** [comment]
Yes you're right. In that case you need to read the resource as a whole and test whether the `socket-binding-port-offset` attribute is defined: 

```java
Operation op = new Operation.Builder(READ_RESOURCE_OPERATION, address).build();
dispatcher.execute(new DMRAction(op), new SimpleCallback<DMRResponse>() {
        @Override
        public void onSuccess(DMRResponse response) {
            ModelNode result = ...;
            if (result.hasDefined("socket-binding-port-offset")) {
            }
        }
    });
```

**Comment by ryanemerson** [comment]
@hpehl I have pushed the requested changes to this PR and https://github.com/hal/core/pull/109

**Comment by hpehl** [comment]
I slightly changed your approach to show the effective port offset in the server preview: The port offset is read dynamically instead of being port of the topology functions.

**Pull request closed without merging**
