### PR TITLE
HAL-1199, JBEAP-6418: add custom validator for naming subsystem

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [HAL-1199](https://issues.jboss.org/browse/HAL-1199)

### CODE REVIEW

**Comment by michpetrov** [comment]
@hpehl the form requires more validation, please don't merge this yet

**Comment by michpetrov** [comment]
Added more checks, rebased and done.

**Comment by hpehl** [comment]
Thanks @michpetrov

**Comment by michpetrov** [comment]
Final adjustment, forgot to null-check.

**Pull request merged**
