### PR TITLE
[BZ1257842]: Edit button is missing in the root logger of "Management Model View"(admin-console)

### PR DESCRIPTION
**Pull request by panossot**
BZ1257842 : https://bugzilla.redhat.com/show_bug.cgi?id=1257842
Upstream : https://github.com/hal/core/commit/8949ed6dc259feb366d17ec2078c7799f32d7763

### CODE REVIEW

**Comment by heiko-braun** [comment]
Interesting, we already another PR for this: #66

But at a first glance your's seems to be more complete. Is this a backport from master?

**Comment by panossot** [comment]
https://github.com/hal/core/pull/66 is the right one. Please ignore https://github.com/hal/core/pull/67.


----- Original Message -----

**Comment by heiko-braun** [comment]
@panossot Do you want me to close the more recent #67?

**Comment by heiko-braun** [comment]
:)

**Comment by panossot** [comment]
Closed it. https://github.com/hal/core/pull/66 is the right one.

**Pull request closed without merging**
